### ISSUE TITLE
Cannot run from flatpak

### ISSUE THREAD

**Issue by TudorAndrei** [squidowl/halloy#341]
I have installed Halloy from flatpak and I get the following error when running it.

```
thread 'main' panicked at /run/build/halloy/cargo/vendor/winit/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /run/build/halloy/cargo/vendor/winit/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x601c5b291756 - <unknown>
   1:     0x601c5b2c25a0 - <unknown>
   2:     0x601c5b28d18f - <unknown>
   3:     0x601c5b291534 - <unknown>
   4:     0x601c5b292e37 - <unknown>
   5:     0x601c5b292b99 - <unknown>
   6:     0x601c5b2932c8 - <unknown>
   7:     0x601c5b2931a2 - <unknown>
   8:     0x601c5b291c56 - <unknown>
   9:     0x601c5b292ef4 - <unknown>
  10:     0x601c5a096f25 - <unknown>
  11:     0x601c5a097473 - <unknown>
  12:     0x601c5a6eff63 - <unknown>
  13:     0x601c5a675eb5 - <unknown>
  14:     0x601c5a1b6954 - <unknown>
  15:     0x601c5a25dd44 - <unknown>
  16:     0x601c5a155cff - <unknown>
  17:     0x601c5a257d03 - <unknown>
  18:     0x601c5a25c98e - <unknown>
  19:     0x601c5a16a3c7 - <unknown>
  20:     0x601c5a25cab6 - <unknown>
  21:     0x601c5a23a3b5 - <unknown>
  22:     0x601c5b284fb1 - <unknown>
  23:     0x601c5a16f155 - <unknown>
  24:     0x7a0a5f23b08a - <unknown>
  25:     0x7a0a5f23b14b - __libc_start_main
  26:     0x601c5a097a15 - <unknown>
  27:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:163:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
```

**Comment by casperstorm** [comment]
This seems like an issue related to winit or iced. Which is the GUI framework we use. 

I am curious if you are able to run the tour example from iced, or does it give you the same error? https://github.com/iced-rs/iced

**Comment by TudorAndrei** [comment]
I was using nightly (1.79.0) to run this (idk if this is useful, after this i changed to stable
```
error[E0658]: use of unstable library feature 'proc_macro_byte_character'
   --> /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.81/src/wrapper.rs:871:21
    |
871 |                     proc_macro::Literal::byte_character(byte)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #115268 <https://github.com/rust-lang/rust/issues/115268> for more information
    = help: add `#![feature(proc_macro_byte_character)]` to the crate attributes to enable
    = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date

error[E0658]: use of unstable library feature 'proc_macro_c_str_literals'
   --> /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.81/src/wrapper.rs:898:21
    |
898 |                     proc_macro::Literal::c_string(string)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #119750 <https://github.com/rust-lang/rust/issues/119750> for more information
    = help: add `#![feature(proc_macro_c_str_literals)]` to the crate attributes to enable
    = note: this compiler was built on 2024-03-27; consider upgrading it if it is out of date

   Compiling crc32fast v1.4.0
   Compiling futures-sink v0.3.30
   Compiling rustc-hash v1.1.0
   Compiling adler v1.0.2
   Compiling futures-channel v0.3.30
   Compiling aho-corasick v1.1.3
   Compiling concurrent-queue v2.4.0
For more information about this error, try `rustc --explain E0658`.
error: could not compile `proc-macro2` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```
On stable (1.76) I got this 
```
2024-04-17T18:50:54.759560Z  WARN winit::platform_impl::platform::x11::xdisplay: error setting XSETTINGS; Xft options won't reload automatically
2024-04-17T18:50:54.773398Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
2024-04-17T18:50:54.824078Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation
2024-04-17T18:50:54.833824Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw
2024-04-17T18:50:54.837634Z  INFO wgpu_hal::gles::egl: Using X11 platform
2024-04-17T18:50:54.839575Z  WARN wgpu_hal::gles::egl: No config found!
2024-04-17T18:50:54.839591Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively
2024-04-17T18:50:54.843630Z  INFO iced_wgpu::window::compositor: Settings {
    present_mode: AutoVsync,
    backends: Backends(
        VULKAN | GL | METAL | DX12 | BROWSER_WEBGPU,
    ),
    default_font: Font {
        family: SansSerif,
        weight: Normal,
        stretch: Normal,
        style: Normal,
    },
    default_text_size: Pixels(
        16.0,
    ),
    antialiasing: None,
}
2024-04-17T18:50:54.849687Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "Intel(R) Graphics (ADL GT2)", vendor: 32902, device: 18086, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2", backend: Vulkan }
2024-04-17T18:50:54.849744Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)", backend: Vulkan }
2024-04-17T18:50:54.849751Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU", vendor: 4318, device: 9376, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.171.04", backend: Vulkan }
2024-04-17T18:50:54.879082Z  INFO wgpu_core::instance: Adapter Gl AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2024-04-17T18:50:54.879184Z  INFO iced_wgpu::window::compositor: Available adapters: [
    AdapterInfo {
        name: "Intel(R) Graphics (ADL GT2)",
        vendor: 32902,
        device: 18086,
        device_type: IntegratedGpu,
        driver: "Intel open-source Mesa driver",
        driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "llvmpipe (LLVM 15.0.7, 256 bits)",
        vendor: 65541,
        device: 0,
        device_type: Cpu,
        driver: "llvmpipe",
        driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2 (LLVM 15.0.7)",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU",
        vendor: 4318,
        device: 9376,
        device_type: DiscreteGpu,
        driver: "NVIDIA",
        driver_info: "535.171.04",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "NVIDIA GeForce RTX 3070 Ti Laptop GPU/PCIe/SSE2",
        vendor: 4318,
        device: 0,
        device_type: Other,
        driver: "",
        driver_info: "",
        backend: Gl,
    },
]
2024-04-17T18:50:54.887302Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "Intel(R) Graphics (ADL GT2)", vendor: 32902, device: 18086, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2", backend: Vulkan }
2024-04-17T18:50:54.887358Z  INFO iced_wgpu::window::compositor: Selected: AdapterInfo {
    name: "Intel(R) Graphics (ADL GT2)",
    vendor: 32902,
    device: 18086,
    device_type: IntegratedGpu,
    driver: "Intel open-source Mesa driver",
    driver_info: "Mesa 23.2.1-1ubuntu3.1~22.04.2",
    backend: Vulkan,
}
2024-04-17T18:50:54.887433Z  INFO iced_wgpu::window::compositor: Available formats: Copied {
    it: Iter(
        [
            Bgra8UnormSrgb,
            Bgra8Unorm,
        ],
    ),
}
2024-04-17T18:50:54.887444Z  INFO iced_wgpu::window::compositor: Available alpha modes: [
    Opaque,
    Inherit,
]
2024-04-17T18:50:54.887452Z  INFO iced_wgpu::window::compositor: Selected format: Bgra8UnormSrgb with alpha mode: Auto
2024-04-17T18:50:55.002803Z ERROR winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
2024-04-17T18:50:55.002848Z ERROR winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
2024-04-17T18:50:55.002860Z ERROR winit::platform_impl::platform: X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
thread 'main' panicked at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/window.rs:1208:18:
Failed to call XMapRaised: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/window.rs:601:34:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x59bb251439c6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x59bb251439c6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x59bb251439c6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x59bb251439c6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x59bb25173090 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x59bb25173090 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x59bb2513fd7f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x59bb251437a4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x59bb251437a4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x59bb25145027 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x59bb25144d89 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x59bb251454b8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x59bb25145392 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x59bb25143ec6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x59bb251450f0 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x59bb2322ceb5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x59bb2322d4f3 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x59bb235664e9 - core::result::Result<T,E>::unwrap::h2bfd18e994fc5225
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
  18:     0x59bb235a1026 - winit::platform_impl::platform::x11::window::UnownedWindow::shared_state_lock::hf488072b55571c4a
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/window.rs:601:9
  19:     0x59bb235a312f - winit::platform_impl::platform::x11::window::UnownedWindow::fullscreen::haaa53b68481b4037
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/window.rs:851:28
  20:     0x59bb23681230 - winit::platform_impl::platform::Window::fullscreen::h1fc618e25d46560e
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/mod.rs:489:50
  21:     0x59bb23637263 - <winit::window::Window as core::ops::drop::Drop>::drop::{{closure}}::hd8de189a523bd30e
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/window.rs:71:53
  22:     0x59bb236811d6 - winit::platform_impl::platform::Window::maybe_wait_on_main::hbeaf2db2b1dee556
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/mod.rs:314:9
  23:     0x59bb2363723b - <winit::window::Window as core::ops::drop::Drop>::drop::hc0750faf63d56072
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/window.rs:66:9
  24:     0x59bb2334b587 - core::ptr::drop_in_place<winit::window::Window>::hbec42a624072a76b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  25:     0x59bb232a6a9e - alloc::sync::Arc<T,A>::drop_slow::h8c109df9e57bcd31
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/sync.rs:1752:18
  26:     0x59bb23355d31 - <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop::h280ba823f3c58382
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/sync.rs:2407:13
  27:     0x59bb2334d6ba - core::ptr::drop_in_place<alloc::sync::Arc<winit::window::Window>>::hce29efb4a9c95862
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
  28:     0x59bb2326d1bf - iced_winit::application::run_instance::{{closure}}::h1a69b98c5150f166
                               at /home/tudor/cave/iced/winit/src/application.rs:324:1
  29:     0x59bb23272237 - iced_winit::application::run::{{closure}}::{{closure}}::h82877624ec54a6ba
                               at /home/tudor/cave/iced/winit/src/application.rs:259:24
  30:     0x59bb2327288f - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::hccac5f3248a61996
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:294:13
  31:     0x59bb233143ee - winit::platform_impl::platform::x11::EventLoop<T>::single_iteration::hc7abf00c88dc65e7
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/mod.rs:548:9
  32:     0x59bb23312e86 - winit::platform_impl::platform::x11::EventLoop<T>::pump_events::h1a745272f35f0818
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/mod.rs:441:13
  33:     0x59bb233136b5 - winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand::hdab368303016ba12
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/x11/mod.rs:408:19
  34:     0x59bb233212fe - winit::platform_impl::platform::EventLoop<T>::run_on_demand::h2db05aff744d4323
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/mod.rs:829:56
  35:     0x59bb23321b76 - winit::platform_impl::platform::EventLoop<T>::run::h95a0c5645153ef17
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/platform_impl/linux/mod.rs:822:9
  36:     0x59bb232b4689 - winit::event_loop::EventLoop<T>::run::h5befa874a900e42c
                               at /home/tudor/.cargo/git/checkouts/winit-57d3141eaf559308/592bd15/src/event_loop.rs:249:9
  37:     0x59bb232719cd - iced_winit::application::run::{{closure}}::h9eaae71cd97d6576
                               at /home/tudor/cave/iced/winit/src/application.rs:274:13
  38:     0x59bb232e6f38 - futures_executor::local_pool::block_on::{{closure}}::hf90a86136a0e222f
                               at /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:317:23
  39:     0x59bb232e6d91 - futures_executor::local_pool::run_executor::{{closure}}::h9ed003b6ee1e56f8
                               at /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:90:37
  40:     0x59bb232649d5 - std::thread::local::LocalKey<T>::try_with::ha84277f93d3379e4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  41:     0x59bb23264311 - std::thread::local::LocalKey<T>::with::hbc561c145193834b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  42:     0x59bb232e6cd4 - futures_executor::local_pool::run_executor::hf0506300dd88dbd3
                               at /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:86:5
  43:     0x59bb232e6eb7 - futures_executor::local_pool::block_on::he8e7e4f6e0eeba93
                               at /home/tudor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:317:5
  44:     0x59bb2337197e - iced::application::Application::run::h423ee81847c4c507
                               at /home/tudor/cave/iced/src/application.rs:234:12
  45:     0x59bb23371fb5 - iced::program::Program<P>::run_with::hd0f01d4acb0fde38
                               at /home/tudor/cave/iced/src/program.rs:247:9
  46:     0x59bb23371afd - iced::program::Program<P>::run::h2dd934666c45d73b
                               at /home/tudor/cave/iced/src/program.rs:171:9
  47:     0x59bb232f6125 - tour::main::h5d415f6489ecaa5f
                               at /home/tudor/cave/iced/examples/tour/src/main.rs:19:5
  48:     0x59bb23342362 - core::ops::function::FnOnce::call_once::h5be4a0512348d680
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  49:     0x59bb233a9555 - std::sys_common::backtrace::__rust_begin_short_backtrace::h14cc0124d696e3ea
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  50:     0x59bb23395f46 - std::rt::lang_start::{{closure}}::h259d045b26e4206f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  51:     0x59bb251389e1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  52:     0x59bb251389e1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  53:     0x59bb251389e1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  54:     0x59bb251389e1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  55:     0x59bb251389e1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  56:     0x59bb251389e1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  57:     0x59bb251389e1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  58:     0x59bb251389e1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  59:     0x59bb251389e1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  60:     0x59bb23395f1a - std::rt::lang_start::h525ec0f0c6669d69
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  61:     0x59bb232fb6be - main
  62:     0x7a01ca229d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  63:     0x7a01ca229e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  64:     0x59bb2322d8b5 - _start
  65:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:163:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    217124 IOT instruction (core dumped)  cargo run --package tour
```

**Comment by casperstorm** [comment]
This is most likely a driver issue then on your end.

**Comment by casperstorm** [comment]
Feel free to re-open with additional information, but for now we can't do much as this seems to be related to the hardware/drivers.

**Comment by dylrich** [comment]
Having the same issue here. I am building from source and can't get the application to launch. Using Nvidia proprietary drivers.

**Comment by dylrich** [comment]
Commenting for posterity: The issue seems to be that something in Halloy's graphics stack was causing NVK to run, which doesn't work when you have proprietary drivers installed. I am on Fedora, and fixed this by uninstalling `mesa-vulkan-drivers.x86`. I had this package installed for Steam, but Steam only depends on the i686 version, so it's safe to remove the 64 bit package. After uninstalling, Halloy works.

There might be something to fix within these GPU libraries because this is the only application that was misbehaving, but it's at least fixable by end users.

**Comment by dylrich** [comment]
I am back again: I am getting this same error on the flatpack now, even with the above package I mentioned uninstalled. When I build Halloy from source and run it works correctly.

**Comment by TiddoLangerak** [comment]
Same as above. The flatpak install doesn't work, regardless of the presence of `mesa-vulkan-drivers`. From source it works as long as `mesa-vulkan-drivers` isn't installed, but with `mesa-vulkan-drivers` installed I'm getting the same panic.

For me this is on Ubuntu with NVIDIA 4080 super + proprietary drivers.
