### ISSUE TITLE
High CPU use on X11 Linux

### ISSUE THREAD

**Issue by wezm** [squidowl/halloy#606]
This issue is in response to a comment I left in a different issue. I think the problems are different: https://github.com/squidowl/halloy/issues/589#issuecomment-2390271608

On my X11 Linux system running AwesomeWM Halloy starts using a large amount of CPU time after a few hours. I'm not sure of the exact time but in this case I started Halloy at 10:32am and noticed it misbehaving at around 2:30pm. I am running a release build of Halloy built from 7690a83.

**Edit:** it does not seem to be time related it uses 160% CPU a few seconds after launching.

<img width="1300" alt="Screenshot from 2024-10-03 14-38-51" src="https://github.com/user-attachments/assets/6bd9cce3-7dc1-40f1-a05f-b6dc6e40ec66">

Halloy itself appears to still be functional. The high CPU is originating in tokio worker threads:

```
$ ps -o pid,lwp,pcpu,comm,cmd  -L 2006312
    PID     LWP %CPU COMMAND         CMD
2006312 2006312  0.3 halloy          target/release/halloy
2006312 2018353  0.0 halloy          target/release/halloy
2006312 2018355  0.0 tokio-runtime-w target/release/halloy
2006312 2018356  0.0 tokio-runtime-w target/release/halloy
2006312 2018357  1.7 tokio-runtime-w target/release/halloy
2006312 2018358  0.0 tokio-runtime-w target/release/halloy
2006312 2018359 10.1 tokio-runtime-w target/release/halloy
2006312 2018360  0.0 tokio-runtime-w target/release/halloy
2006312 2018361  0.0 tokio-runtime-w target/release/halloy
2006312 2018362  0.0 tokio-runtime-w target/release/halloy
2006312 2018363  2.2 tokio-runtime-w target/release/halloy
2006312 2018364  0.0 tokio-runtime-w target/release/halloy
2006312 2018365  1.8 tokio-runtime-w target/release/halloy
2006312 2018366  0.0 tokio-runtime-w target/release/halloy
2006312 2018367  0.0 tokio-runtime-w target/release/halloy
2006312 2018368  2.4 tokio-runtime-w target/release/halloy
2006312 2018369  0.0 tokio-runtime-w target/release/halloy
2006312 2018370  0.0 tokio-runtime-w target/release/halloy
2006312 2018371  0.0 tokio-runtime-w target/release/halloy
2006312 2018372  0.0 tokio-runtime-w target/release/halloy
2006312 2018373 33.0 tokio-runtime-w target/release/halloy
2006312 2018374  0.0 tokio-runtime-w target/release/halloy
2006312 2018375  0.0 tokio-runtime-w target/release/halloy
2006312 2018376  0.0 tokio-runtime-w target/release/halloy
2006312 2018377  0.0 tokio-runtime-w target/release/halloy
2006312 2018378  2.4 tokio-runtime-w target/release/halloy
2006312 2018379 22.9 tokio-runtime-w target/release/halloy
2006312 2018380 32.2 tokio-runtime-w target/release/halloy
2006312 2018381  0.0 tokio-runtime-w target/release/halloy
2006312 2018382  0.0 tokio-runtime-w target/release/halloy
2006312 2018383 22.6 tokio-runtime-w target/release/halloy
2006312 2018384 25.8 tokio-runtime-w target/release/halloy
2006312 2018385  0.0 tokio-runtime-w target/release/halloy
2006312 2018386  0.0 tokio-runtime-w target/release/halloy
2006312 2018390  0.0 async-io        target/release/halloy
2006312 2018391  0.0 zbus::Connectio target/release/halloy
2006312 2018393  0.0 halloy:cs0      target/release/halloy
2006312 2018394  0.0 halloy:disk$0   target/release/halloy
2006312 2018395  0.0 halloy:sh0      target/release/halloy
2006312 2018396  0.0 halloy:sh_opt0  target/release/halloy
2006312 2018397  0.0 halloy:traceq0  target/release/halloy
2006312 2018398  0.0 halloy:traceq0  target/release/halloy
2006312 2018399  0.0 halloy:traceq0  target/release/halloy
2006312 2018400  0.0 halloy:gdrv0    target/release/halloy
2006312 2018401  0.0 halloy:gl0      target/release/halloy
2006312 2018402  0.0 halloy:disk$0   target/release/halloy
2006312 2018403  0.0 halloy          target/release/halloy
2006312 2018404  0.0 halloy          target/release/halloy
2006312 2018405  0.0 halloy          target/release/halloy
2006312 2018406  0.0 halloy          target/release/halloy
2006312 2018407  0.0 halloy          target/release/halloy
2006312 2018408  0.0 halloy          target/release/halloy
2006312 2018409  0.0 halloy          target/release/halloy
2006312 2018410  0.0 halloy          target/release/halloy
2006312 2018411  0.0 halloy          target/release/halloy
2006312 2018412  0.0 halloy          target/release/halloy
2006312 2018413  0.0 halloy          target/release/halloy
2006312 2018414  0.0 halloy          target/release/halloy
2006312 2018415  0.0 halloy          target/release/halloy
2006312 2018416  0.0 halloy          target/release/halloy
2006312 2018417  0.0 halloy          target/release/halloy
2006312 2018418  0.0 halloy          target/release/halloy
2006312 2018419  0.0 halloy          target/release/halloy
2006312 2018420  0.0 halloy          target/release/halloy
2006312 2018421  0.0 halloy          target/release/halloy
2006312 2018422  0.0 halloy          target/release/halloy
2006312 2018423  0.0 halloy          target/release/halloy
2006312 2018424  0.0 halloy          target/release/halloy
2006312 2018425  0.0 halloy          target/release/halloy
2006312 2018426  0.0 halloy          target/release/halloy
2006312 2018427  0.0 halloy          target/release/halloy
2006312 2018428  0.0 halloy          target/release/halloy
2006312 2018429  0.0 halloy          target/release/halloy
2006312 2018430  0.0 halloy          target/release/halloy
2006312 2018431  0.0 halloy          target/release/halloy
2006312 2018432  0.0 halloy          target/release/halloy
2006312 2018433  0.0 halloy          target/release/halloy
2006312 2018434  0.0 halloy          target/release/halloy
2006312 2018437  0.0 halloy          target/release/halloy
2006312 2018450  0.0 WSI swapchain q target/release/halloy
2006312 2018451  0.0 WSI swapchain e target/release/halloy
```

Looking at what thread 2018373 is doing in `gdb` just shows it doing `futex_wait`:

```
[Switching to thread 63 (Thread 0x70e6666006c0 (LWP 2018373))]
#0  0x000070e66fc371fd in syscall () from /usr/lib/libc.so.6
(gdb) bt
#0  0x000070e66fc371fd in syscall () from /usr/lib/libc.so.6
#1  0x000061585b7cabe9 in parking_lot_core::thread_parker::imp::ThreadParker::futex_wait ()
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.10/src/thread_parker/linux.rs:112
#2  parking_lot_core::thread_parker::imp::{impl#0}::park (self=0x70e666600640)
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.10/src/thread_parker/linux.rs:66
#3  parking_lot_core::parking_lot::park::{closure#0}<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}> (thread_data=0x70e666600620)
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.10/src/parking_lot.rs:635
#4  parking_lot_core::parking_lot::with_thread_data<parking_lot_core::parking_lot::ParkResult, parking_lot_core::parking_lot::park::{closure_env#0}<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}>> (f=...)
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.10/src/parking_lot.rs:207
#5  parking_lot_core::parking_lot::park<parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#0}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#1}, parking_lot::condvar::{impl#1}::wait_until_internal::{closure_env#2}> (key=<optimized out>, validate=..., before_sleep=...,
    timed_out=..., park_token=..., timeout=<error reading variable: Cannot access memory at address 0x8>)
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.10/src/parking_lot.rs:600
#6  parking_lot::condvar::Condvar::wait_until_internal (self=0x615868632320, mutex=0x615868632328, timeout=...) at src/condvar.rs:334
#7  0x000061585b7993be in parking_lot::condvar::Condvar::wait<()> (self=<optimized out>, mutex_guard=<optimized out>)
    at /home/wmoore/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot-0.12.3/src/condvar.rs:256
#8  tokio::loom::std::parking_lot::Condvar::wait<()> (self=0x615868632320, guard=...) at src/loom/std/parking_lot.rs:149
#9  tokio::runtime::scheduler::multi_thread::park::Inner::park_condvar (self=0x615868632310) at src/runtime/scheduler/multi_thread/park.rs:158
#10 tokio::runtime::scheduler::multi_thread::park::Inner::park (self=0x615868632310, handle=<error reading variable: Cannot access memory at address 0x0>)
[snip]
```

`perf top` also shows a lot of time in futexes and strangely `getenv`:

<img width="962" alt="Screenshot from 2024-10-03 14-52-28" src="https://github.com/user-attachments/assets/897bb26e-7719-46fe-9b60-30f3f4fd09ce">

`strace` shows a lot of `EAGAIN` errors, not sure if this is noteworthy:

```
$ doas strace -p 2006312
strace: Process 2006312 attached
timerfd_settime(9, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
epoll_ctl(5, EPOLL_CTL_MOD, 9, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=0, u64=4294967296}}], 1024, -1) = 1
read(6, 0x7ffc19d113f0, 8)              = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(5, EPOLL_CTL_MOD, 6, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
read(10, "\2\0\0\0\0\0\0\0", 8)         = 8
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
write(10, "\2\0\0\0\0\0\0\0", 8)        = 8
poll([{fd=4, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=4, revents=POLLOUT}])
writev(4, [{iov_base="\16\0\2\0\3\0\0\5", iov_len=8}], 1) = 8
poll([{fd=4, events=POLLIN}], 1, -1)    = 1 ([{fd=4, revents=POLLIN}])
recvmsg(4, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\30D\233\0\0\0\0X\4\0\0\0\0\0\0\253\7\300\5\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
write(10, "\2\0\0\0\0\0\0\0", 8)        = 8
statx(AT_FDCWD, "/etc/localtime", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFLNK|0777, stx_size=38, ...}) = 0
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
timerfd_settime(9, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
epoll_ctl(5, EPOLL_CTL_MOD, 9, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=0, u64=4294967296}}], 1024, 0) = 1
read(6, 0x7ffc19d113f0, 8)              = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(5, EPOLL_CTL_MOD, 6, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
read(10, "\4\0\0\0\0\0\0\0", 8)         = 8
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
ioctl(131, DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT, 0x7ffc19d0ad90) = 0
ioctl(127, DMA_BUF_IOCTL_EXPORT_SYNC_FILE, 0x7ffc19d0afc0) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_CREATE, 0x7ffc19d0af30) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_FD_TO_HANDLE, 0x7ffc19d0afa0) = 0
close(333)                              = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT, 0x7ffc19d09b20) = 0
ioctl(131, DRM_IOCTL_AMDGPU_CS, 0x7ffc19d09690) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_RESET, 0x7ffc19d09c10) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_DESTROY, 0x7ffc19d09bf0) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_QUERY, 0x7ffc19d0a5b0) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_WAIT, 0x7ffc19d0b690) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_RESET, 0x7ffc19d0b890) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT, 0x7ffc19d0ad80) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD, 0x7ffc19d0a920) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD, 0x7ffc19d0a920) = 0
ioctl(333, SYNC_IOC_MERGE, 0x7ffc19d0abc0) = 0
close(333)                              = 0
close(338)                              = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_FD_TO_HANDLE, 0x7ffc19d0a930) = 0
close(339)                              = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_TRANSFER, 0x7ffc19d0a920) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_TRANSFER, 0x7ffc19d0a920) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_RESET, 0x7ffc19d0aea0) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT, 0x7ffc19d0b710) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD, 0x7ffc19d0b820) = 0
ioctl(131, DRM_IOCTL_SYNCOBJ_RESET, 0x7ffc19d0b830) = 0
ioctl(127, BINDER_SET_IDLE_TIMEOUT or DMA_BUF_IOCTL_IMPORT_SYNC_FILE, 0x7ffc19d0b890) = 0
close(333)                              = 0
futex(0x615869c13c8c, FUTEX_WAKE_PRIVATE, 1) = 1
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
futex(0x6158685bc928, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x6158685b7820, FUTEX_WAKE_PRIVATE, 1) = 1
timerfd_settime(9, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
epoll_ctl(5, EPOLL_CTL_MOD, 9, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
epoll_wait(5, [{events=EPOLLIN, data={u32=0, u64=0}}], 1024, -1) = 1
read(6, 0x7ffc19d113f0, 8)              = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(5, EPOLL_CTL_MOD, 6, {events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLONESHOT, data={u32=4294967295, u64=18446744073709551615}}) = 0
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
timerfd_settime(9, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}) = 0
```

Lastly [the Wikipedia article on Futex](https://en.wikipedia.org/wiki/Futex) says:

> A properly programmed futex-based lock will not use system calls except when the lock has contention;

So perhaps there is some lock contention/deadlock happening?

### Environment

OS: Arch Linux (x86_64)
Rust Version: rustc 1.81.0 (eeb90cda1 2024-09-04)

**Comment by wezm** [comment]
Closing this as I think it's resolved. I built fbbde68 and the idle cpu time is now 0-0.5%
