### ISSUE TITLE
[NixOS /unstable] [GNOME] Halloy logs me out on launch

### ISSUE THREAD

**Issue by RooterDelWifi** [squidowl/halloy#638]
The title pretty much speaks for itself

DE: GNOME 46.4
OS: NixOS 24.11
Package: nixpkgs unstable

**Comment by RooterDelWifi** [comment]
```
rooter@nixos:~/Dev/Repos/halloy/ > RUST_BACKTRACE=full target/release/halloy
thread 'main' panicked at /home/rooter/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/d660fad/winit/src/program.rs:192:10:
Create event loop: NotSupported(NotSupportedError)
stack backtrace:
   0:     0x56337538791a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hb3f5a3247191e339
   1:     0x5633753b578b - core::fmt::write::h22289eafac2f838b
   2:     0x5633753824c3 - std::io::Write::write_fmt::hd763af197f3aed71
   3:     0x563375387762 - std::sys::backtrace::BacktraceLock::print::h76d88db97e580f22
   4:     0x563375388897 - std::panicking::default_hook::{{closure}}::h184d09c0d0bc099f
   5:     0x5633753886c6 - std::panicking::default_hook::h42d0838ed54df860
   6:     0x563375388ed7 - std::panicking::rust_panic_with_hook::hbc158dc145985f20
   7:     0x563375388d77 - std::panicking::begin_panic_handler::{{closure}}::ha4ff8d0a34f0db3b
   8:     0x563375387df9 - std::sys::backtrace::__rust_end_short_backtrace::h99054fe005abe325
   9:     0x563375388a04 - rust_begin_unwind
  10:     0x5633753b2843 - core::panicking::panic_fmt::h700376aebf176cba
  11:     0x5633753b2c86 - core::result::unwrap_failed::heb1fa387050f2027
  12:     0x563373ff8001 - iced::program::Program::run_with::h20df6842352cac49
  13:     0x5633741a0824 - halloy::main::h5bd305dcac64aeaf
  14:     0x563374023ee3 - std::sys::backtrace::__rust_begin_short_backtrace::h5e4b5d3ab34f2e1b
  15:     0x56337416a0c9 - std::rt::lang_start::{{closure}}::hc255bbbe9a58be84
  16:     0x56337537a3e0 - std::rt::lang_start_internal::h7e913160d7559c95
  17:     0x5633741a24e5 - main
  18:     0x7f22d8c3314e - __libc_start_call_main
  19:     0x7f22d8c33209 - __libc_start_main@GLIBC_2.2.5
  20:     0x563373e0ca65 - _start
  21:                0x0 - <unknown>
rooter@nixos:~/Dev/Repos/halloy/ > WINIT_UNIX_BACKEND=x11 target/release/halloy
thread 'main' panicked at /home/rooter/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/d660fad/winit/src/program.rs:192:10:
Create event loop: NotSupported(NotSupportedError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to build the app from source and run it, this is the backtrace

**Comment by casperstorm** [comment]
This looks like your GPU or driver isn't supported.
You could try to just compile our GUI backend, eg their "tour" example from here: https://github.com/iced-rs/iced
If that also fails, it is GPU related, on your end.

**Comment by RooterDelWifi** [comment]
this seems to be an error in how nixos handles dynamic libraries: https://github.com/rust-windowing/winit/issues/3603, here https://github.com/rust-windowing/winit/issues/3603#issuecomment-2029748871 solved this by telling cargo to add `NIX_LD_LIBRARY_PATH` to the rustc linker library search paths
